---
# General configuration
APPLY_FIXES: 'all'
SARIF_REPORTER: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
VALIDATE_ALL_CODEBASE: true

# Disable hadolint errors for now
DOCKERFILE_HADOLINT_DISABLE_ERRORS: true

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM

DISABLE:
  - SPELL

PYTHON_BANDIT_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
