---
version: 2.1

# define the parameters from the setup config.
parameters:
  build-fedora-image:
    type: boolean
    default: false
  build-circleci-node-image:
    type: boolean
    default: false

jobs:
  build-circleci-node-image:
    working_directory: node/
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      DOCKER_VERSION_TAG: v1.0.0
      DOCKER_IMAGE_NAME: circleci-pnpm
      GITHUB_USERNAME: relativesure
      GITHUB_ORG: kubearchitect
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and pushDocker image
          command: |
            TAG=$DOCKER_VERSION_TAG.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$TAG $CIRCLE_WORKING_DIRECTORY         
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$TAG

workflows:
  build-circleci-node-image-workflow:
    jobs:
      - build-circleci-node-image:
          context:
            - main-context
