---
version: 2.1

# define the parameters from the setup config.
parameters:
  build-fedora-image:
    type: boolean
    default: false
  build-circleci-node-image:
    type: boolean
    default: false

jobs:
  build-circleci-node-image:
    working_directory: node/
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      DOCKER_VERSION_TAG: v1.0.0
      DOCKER_IMAGE_NAME: circleci-pnpm
      GITHUB_USERNAME: relativesure
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t ghcr.io/$GITHUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_VERSION_TAG-$CIRCLE_BUILD_NUM $CIRCLE_WORKING_DIRECTORY
      - run:
          name: List Docker image
          command: docker image ls
      - run:
          name: Push application Docker image
          command: |
            # RelativeSure Classic Token
            echo $RS_GH_PACKAGES_TOKEN_v2 | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker push ghcr.io/$GITHUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_VERSION_TAG-$CIRCLE_BUILD_NUM

workflows:
  build-circleci-node-image-workflow:
    jobs:
      - build-circleci-node-image:
          context:
            - main-context
