---
version: 2.1

orbs:
  megalinter: relativesure/megalinter@1.0.5
  github-cli: circleci/github-cli@2.6.2

# define the parameters from the setup config.  
parameters:  
  megalinter:  
    type: boolean  
    default: false  
  build-fedora-image:  
    type: boolean  
    default: false

jobs:
  after-megalinter:
    docker:
      - image: cimg/base:stable
        auth: 
           username: $DOCKER_HUB_USER
           password: $DOCKER_HUB_PASSWORD
    steps:
      - attach_workspace:
          at: /tmp/lint
      - run:
          name: Get the updated sources in megalinter-reports
          command: |
            # List the folders in updated_sources within megainter-reports
            FOLDER_LIST=$(ls -l /tmp/lint/megalinter-reports/updated_sources)
            echo "Folders in /tmp/lint/megalinter-reports/updated_sources: $FOLDER_LIST"
            if [ -z "$FOLDER_LIST" ]; then
              echo "No updated sources found"
              exit 0
            else
              echo "Updated sources found. Copying files to the root of the repository"
              for folder in $FOLDER_LIST; do
                echo "Folder: $folder"
                # Copy the updated sources to the root of the repository
                cp -r /tmp/lint/megalinter-reports/updated_sources/$folder/.* .
                ls -lA
              done
            fi
      - github-cli/setup:
          token: GH_PACKAGES_TOKEN
      - run:
          name: Set up Git bot
          command: |
              git config --local user.email "139585163+KubeArchitectBot@users.noreply.github.com"
              git config --local user.name "KubeArchitectBot"
      - run:
          name: Create a new branch and commit the changes to the repository
          command: |
              git checkout -b megalinter-fixes-$CIRCLE_BUILD_NUM \
              && git commit -am '[MegaLinter] Apply linters automatic fixes' \
              && git push --set-upstream origin megalinter-fixes-$CIRCLE_BUILD_NU
      - run:
          name: Create a pull request
          command: |
              gh pr create --title "[MegaLinter] Apply linters automatic fixes" --body "This PR applies automatic fixes from the MegaLinter" --base master --head megalinter-fixes-$CIRCLE_BUILD_NUM
workflows:
  run-megalinter:
    jobs:
      - megalinter/megalinter:
          persist_megalinter_reports: true
      - after-megalinter:
          requires:
            - megalinter/megalinter