---
version: 2.1

orbs:
  megalinter: relativesure/megalinter@1.0.6
  github-cli: circleci/github-cli@2.6.2

# define the parameters from the setup config.
parameters:
  megalinter:
    type: boolean
    default: false
  build-fedora-image:
    type: boolean
    default: false

jobs:
  megalinter:
    executor:
      flavor: "cupcake"
    - megalinter/megalinter:
        github_token: GH_PACKAGES_TOKEN
        persist_megalinter_reports: true
        run_git_operations: true
        git_base_branch: master
        context:
          - Main Context

workflows:
  run-megalinter:

