---
version: 2.1

orbs:
  megalinter: relativesure/megalinter@1.0.5
  github-cli: circleci/github-cli@2.6.2

# define the parameters from the setup config.
parameters:
  megalinter:
    type: boolean
    default: false
  build-fedora-image:
    type: boolean
    default: false

jobs:
  after-megalinter:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/lint
      - run:
          name: Get the updated sources in megalinter-reports
          command: |
            # List the folders and files in updated_sources within megainter-reports
            ITEMS=$(ls -A /tmp/lint/megalinter-reports/updated_sources | grep -v '^\.$' | grep -v '^\.\.$')
            echo "Items in /tmp/lint/megalinter-reports/updated_sources: $ITEMS"
            # Check if there are any items in updated_sources
            if [ -z "$ITEMS" ]; then
              echo "No updated sources found"
              exit 0
            else
              echo "Updated sources found. Copying files to the repository"
              cp -a /tmp/lint/megalinter-reports/updated_sources/. .
            fi
      - github-cli/setup:
          token: GH_PACKAGES_TOKEN
      - run:
          name: Set up Git bot
          command: |
            git config --local user.email "139585163+KubeArchitectBot@users.noreply.github.com"
            git config --local user.name "KubeArchitectBot"
      - run:
          name: Create a new branch and commit the changes to the repository
          command: |
            git checkout -b megalinter-fixes-$CIRCLE_BUILD_NUM \
            && git add . \
            && git commit -m '[MegaLinter] Apply linters automatic fixes' \
            && git push --set-upstream origin megalinter-fixes-$CIRCLE_BUILD_NUM
      - run:
          name: Create a pull request
          command: |
            gh pr create --title "[MegaLinter] Apply linters automatic fixes" --body "This PR applies automatic fixes from MegaLinter" --base master --head megalinter-fixes-$CIRCLE_BUILD_NUM
workflows:
  run-megalinter:
    jobs:
      - megalinter/megalinter:
          persist_megalinter_reports: true
      - after-megalinter:
          requires:
            - megalinter/megalinter
          filters:
            branches:
              only:
                - master
