---
version: 2.1

orbs:
  megalinter: relativesure/megalinter@1.0.3

# define the parameters from the setup config.  
parameters:  
  megalinter:  
    type: boolean  
    default: false  
  build-fedora-image:  
    type: boolean  
    default: false

workflows:
  run-megalinter:
    jobs:
      - megalinter/megalinter

# jobs:
#   megalinter:
#     docker:
#       - image: oxsecurity/megalinter-cupcake:v8.3.0
#         auth: 
#            username: $DOCKER_HUB_USER
#            password: $DOCKER_HUB_PASSWORD
#     resource_class: large
#     steps: 
#       - checkout  
#       - run:
#           name: ml
#           command: |
#             export GITHUB_TOKEN=$GH_PACKAGES_TOKEN
#             export CI_ACTION_RUN_URL=$CIRCLE_BUILD_URL
#             export GITHUB_REPOSITORY=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
#             export GITHUB_REF=$CI_PULL_REQUEST
#             export GITHUB_SHA=$CIRCLE_SHA1
#             export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY
#             export GITHUB_WORKSPACE=$CIRCLE_WORKING_DIRECTORY
#             export GITHUB_RUN_ID=$CIRCLE_BUILD_NUM
#             /bin/bash -ex /entrypoint.sh
#       - run:
#           name: Get the updated sources in megalinter-reports
#           command: |
#             # List the folders in updated_sources within megainter-reports
#             FOLDER_LIST=$(ls -l megalinter-reports/updated_sources)
#             echo "Folders in megalinter-reports/updated_sources: $FOLDER_LIST"
#             if [ -z "$FOLDER_LIST" ]; then
#               echo "No updated sources found"
#               exit 0
#             else
#               echo "Updated sources found. Copying files to the root of the repository"
#               for folder in $FOLDER_LIST; do
#                 echo "Folder: $folder"
#                 # Copy the updated sources to the root of the repository
#                 cp -r megalinter-reports/updated_sources/$folder/.* .
#                 ls -lA
#               done
#             fi
#       - run:
#           name: Set up Git bot
#           command: |
#             git config --local user.name "github-actions[bot]"
#             git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#       - run:
#           name: Commit changes
#           command: |
#             git add .
#             git commit -m "Apply fixes"
#             git push origin $CIRCLE_BRANCH
#       - store_artifacts:
#           path: megalinter-reports

# workflows:
#   megalinter-workflow:
#     jobs:
#       - megalinter