---
version: 2.1

# define the parameters from the setup config.
parameters:
  build-fedora-image:
    type: boolean
    default: false
  build-circleci-node-image:
    type: boolean
    default: false

jobs:
  no-updates:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "No updates have been made"

workflows:
  no-update-workflow:
    jobs:
      - no-updates
